name: format-check

on:
  push:
    paths:
      - "**.py"
      - ".github/workflows/black-check.yml"
      - "pyproject.toml"
  pull_request:
    paths:
      - "**.py"
      - ".github/workflows/black-check.yml"
      - "pyproject.toml"

jobs:
  black:
    name: Check formatting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install formatter
        run: |
          python -m pip install --upgrade pip
          pip install black

      - name: Run formatter in check mode
        run: |
          black --check coruscant