name: format-check

on:
  push:
    paths:
      - "**.py"
      - ".github/workflows/format.yaml"
      - "pixi.lock"
      - "pyproject.toml"
  pull_request:
    paths:
      - "**.py"
      - ".github/workflows/format.yaml"
      - "pixi.lock"
      - "pyproject.toml"

jobs:
  black:
    name: Check formatting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up pixi
        uses: prefix-dev/setup-pixi@v0.9.4
        with:
          pixi-version: v0.68.1
          manifest-path: pyproject.toml
          cache: true

      - name: Run formatter in check mode
        run: pixi run format-check