name: pixi-tests

on:
  push:
    paths:
      - "coruscant/**"
      - "tests/**"
      - ".github/workflows/tests.yaml"
      - "pixi.lock"
      - "pyproject.toml"
      - "setup.sh"
  pull_request:
    paths:
      - "coruscant/**"
      - "tests/**"
      - ".github/workflows/tests.yaml"
      - "pixi.lock"
      - "pyproject.toml"
      - "setup.sh"

jobs:
  test:
    name: Run pytest with pixi
    runs-on: ubuntu-latest
    env:
      MPLBACKEND: Agg

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up pixi
        uses: prefix-dev/setup-pixi@v0.9.4
        with:
          pixi-version: v0.68.1
          manifest-path: pyproject.toml
          cache: true

      - name: Run pytest
        run: pixi run test